#!/usr/bin/env bash

die() {
    warn "$@"
    exit 1
}
warn() {
    printf >&2 "%s\n" "$*"
}

say() {
    printf "%s\n" "$*"
}

if ! [[ -d ical/ ]] || ! [[ -f calendars.json ]]; then
    
    if [[ -e ical ]] || [[ -e calendars.json ]]
    then
        die "You seem to have an ical/ or calendars.json dir. Move them away and try again."
    fi

    warn "no ical/ or config file found. Trying to download them..."
    set -o pipefail
    reponame=heb-esi.github.io
    repobase=https://github.com/HEB-ESI
    branch=gh-pages
    if wget -O- "$repobase/$repourl/archive/refs/heads/$branch.tar.gz" |
            tar -zx --strip-components=1 "$reponame-$branch/ical" "$reponame-$branch/calendars.json"
    then
        warn "that seems to have worked. great !"
    else
        die "Could not retrieve ical + config file. Grab 'em at $repobase/$repourl/tree/$branch/ical"
    fi
    
fi

docker run --rm \
       --user "$(id -u):$(id -g)" \
       -it \
       -p 8080:8080 \
       -w /app \
       -v "$(pwd)":/app \
       node:16-alpine \
       sh -c "yarn install && yarn serve"
